[phases.setup]
nixPkgs = ["nodejs", "pnpm"]

[phases.install]
cmds = [
  "corepack enable",
  "corepack prepare pnpm@10.26.1 --activate",
  "pnpm install --frozen-lockfile"
]

[variables]
NPM_CONFIG_PRODUCTION = "false"
